# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'firebase_notification' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  # Pods for firebase_notification
  
  target 'firebase_notificationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'firebase_notification-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for firebase_notification-tvOS

  target 'firebase_notification-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
